build:
	gcc 01readFileGetFileGrThTenByte.c -o 01readFileGetFileGrThTenByte.o

clean:
	rm -rf 01readFileGetFileGrThTenByte.o

help:
	@echo '[USAGE] make build && make run ARGS="filename"'

run:
	./01readFileGetFileGrThTenByte.o ${ARGS}