build:
	gcc 06moveDirContet.c -o 06moveDirContet.o

clean:
	rm -rf *06moveDirContet.o
	rm -rf dest/*

help:
	@echo '[USAGE] make build && make run ARGS="sourceFolderName destinationFolderName"'

run:
	./06moveDirContet.o ${ARGS}
