build:
	gcc 03ThreadWithoutSyncProblem.c -o 03ThreadWithoutSyncProblem.o -lpthread

clean:
	rm -rf 03ThreadWithoutSyncProblem.o

help:
	@echo '[USAGE] make build && make run'

run:
	./03ThreadWithoutSyncProblem.o ${ARGS}