build:
	gcc 02readStructFromFile.c -o 02readStructFromFile.o

clean:
	rm -rf 02readStructFromFile.o

help:
	@echo '[USAGE] make build && make run ARGS="filename"'

run:
	./02readStructFromFile.o ${ARGS}