build:
	gcc 01ioRedirection.c -o 01ioRedirection.o

clean:
	rm -rf 01ioRedirection.o

help:
	@echo '[USAGE] make build && make run ARGS="InputfilePath outputFilePath"'

run:
	./01ioRedirection.o ${ARGS}