build:
	gcc 03checkFileEqContent.c -o 03checkFileEqContent.o

clean:
	rm -rf 03checkFileEqContent.o

help:
	@echo '[USAGE] make build && make run ARGS="fileName1 fileName2"'

run:
	./03checkFileEqContent.o ${ARGS}