build:
	gcc 05rmDataFromOffset.c -o 05rmDataFromOffset.o

clean:
	rm -rf 05rmDataFromOffset.o

help:
	@echo '[USAGE] make build && make run ARGS="fileName offset"'

run:
	./05rmDataFromOffset.o ${ARGS}