build:
	gcc 04readDirWriteAllContent.c -o 04readDirWriteAllContent.o

clean:
	rm -rf 04readDirWriteAllContent.o
	rm -rf data.txt

help:
	@echo '[USAGE] make build && make run ARGS="dirname"'

run:
	./04readDirWriteAllContent.o ${ARGS}