build:
	gcc 04copyTenBitesFromAllFiles.c -o 04copyTenBitesFromAllFiles.o

clean:
	rm -rf 04copyTenBitesFromAllFiles.o
	rm -rf ./demo.txt

help:
	@echo '[USAGE] make build && make run ARGS="directoryName"'

run:
	./04copyTenBitesFromAllFiles.o ${ARGS}
