build:
	gcc 04delFileGrTh100Byte.c -o 04delFileGrTh100Byte.o

clean:
	rm -rf 04delFileGrTh100Byte.o

help:
	@echo '[USAGE] make build && make run ARGS="directoryName"'

run:
	./04delFileGrTh100Byte.o ${ARGS}