build:
	gcc 05isFilePresentInDir.c -o 05isFilePresentInDir.o

clean:
	rm -rf 05isFilePresentInDir.o

help:
	@echo '[USAGE] make build && make run ARGS="DirectoryName FileName"'

run:
	./05isFilePresentInDir.o ${ARGS}
