build:
	gcc 06crHoleTruncateHole.c -o 06crHoleTruncateHole.o

clean:
	rm -rf 06crHoleTruncateHole.o

help:
	@echo '[USAGE] make build && make run ARGS="directoryName"'

run:
	./06crHoleTruncateHole.o ${ARGS}