build:
	gcc 07deleteEmptyFilesInDir.c -o 07deleteEmptyFilesInDir.o

clean:
	rm -rf 07deleteEmptyFilesInDir.o

help:
	@echo '[USAGE] make build && make run ARGS="FolderName"'

run:
	./07deleteEmptyFilesInDir.o ${ARGS}
