build:
	gcc 07writeNameInFile.c -o 07writeNameInFile.o

clean:
	rm -rf 07writeNameInFile.o

help:
	@echo '[USAGE] make build && make run ARGS="filename yourName"'

run:
	./07writeNameInFile.o ${ARGS}
