build:
	gcc 03readDirAllWriteInfo.c -o 03readDirAllWriteInfo.o

clean:
	rm -rf 03readDirAllWriteInfo.o

help:
	@echo '[USAGE] make build && make run ARGS="dirname"'

run:
	./03readDirAllWriteInfo.o ${ARGS}