build:
	gcc 03createFileInDir.c -o 03createFileInDir.o

clean:
	rm -rf 03createFileInDir.o

help:
	@echo '[USAGE] make build && make run ARGS="directoryname filename"'

run:
	./03createFileInDir.o ${ARGS}