build:
	gcc 01writeStructInFile.c -o 01writeStructInFile.o

clean:
	rm -rf 01writeStructInFile.o

help:
	@echo '[USAGE] make build && make run ARGS="id name salary"'

run:
	./01writeStructInFile.o ${ARGS}