build:
	gcc 03openDirLargestFile.c -o 03openDirLargestFile.o

clean:
	rm -rf 03openDirLargestFile.o

help:
	@echo '[USAGE] make build && make run ARGS="FolderName"'

run:
	./03openDirLargestFile.o ${ARGS}